name: Brian Kelly
markdown: redcarpet

# the following are always overwritten as described by github pages
# https://help.github.com/articles/using-jekyll-with-pages
safe: true
lsi: false
pygments: true

# source: is set to my top-level dir by github pages
