name: Brian Kelly
markdown: kramdown

exclude: [Gemfile*, README.md]
# permalink: pretty # effectively, /:year/:month/:day/:title
permalink: /:year/:month/:title

# the following are always overwritten as described by github pages
# https://help.github.com/articles/using-jekyll-with-pages
safe: true
lsi: false
highlighter: pygments

# source: is set to my top-level dir by github pages
